use std::fs;
use std::path::{Path, PathBuf};

use chrono::{SecondsFormat, Utc};
use serde::Serialize;
use serde_json::Value;
use sha2::{Digest, Sha256};

#[derive(Debug, Clone)]
pub struct EvidenceArgs {
    pub target: PathBuf,
    pub signatures: PathBuf,
    pub reports: Vec<PathBuf>,
    pub output: PathBuf,
}

#[derive(Debug, Serialize)]
struct EvidenceManifest {
    tool: String,
    manifest_type: String,
    generated_at: String,
    inputs: EvidenceInputs,
    demo_tree: Vec<FileEvidence>,
    reports: Vec<ReportEvidence>,
    reproducibility: Reproducibility,
    safety: Safety,
}

#[derive(Debug, Serialize)]
struct EvidenceInputs {
    target: TargetEvidence,
    signature_database: FileEvidence,
}

#[derive(Debug, Serialize)]
struct TargetEvidence {
    path: String,
    kind: String,
}

#[derive(Debug, Serialize)]
struct FileEvidence {
    path: String,
    sha256: String,
    size_bytes: u64,
}

#[derive(Debug, Serialize)]
struct ReportEvidence {
    path: String,
    sha256: String,
    size_bytes: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    tool: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    target: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    summary: Option<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    scan_metadata: Option<Value>,
}

#[derive(Debug, Serialize)]
struct Reproducibility {
    format_command: String,
    test_command: String,
    lint_command: String,
    signature_validation_command: String,
    eicar_preparation_command: String,
    demo_verification_command: String,
    scan_command: String,
    evidence_manifest_command: String,
}

#[derive(Debug, Serialize)]
struct Safety {
    read_only_scanner: bool,
    uses_live_malware: bool,
    executes_scanned_files: bool,
    mutates_scanned_files: bool,
    network_actions: bool,
    fixture_note: String,
}

pub fn write_evidence_manifest(args: &EvidenceArgs) -> Result<(), String> {
    let target = existing_path(&args.target)?;
    let signatures = existing_path(&args.signatures)?;
    let reports = args
        .reports
        .iter()
        .map(|report| existing_path(report))
        .collect::<Result<Vec<_>, _>>()?;

    let manifest = EvidenceManifest {
        tool: "Sentinel Virus Scanner".to_string(),
        manifest_type: "rust-demo-evidence".to_string(),
        generated_at: Utc::now().to_rfc3339_opts(SecondsFormat::Secs, true),
        inputs: EvidenceInputs {
            target: TargetEvidence {
                path: display_project_path(&target),
                kind: target_kind(&target),
            },
            signature_database: file_evidence(&signatures, &project_root())?,
        },
        demo_tree: demo_tree_evidence(&target)?,
        reports: reports
            .iter()
            .map(|report| report_evidence(report))
            .collect::<Result<Vec<_>, _>>()?,
        reproducibility: reproducibility(
            &args.target,
            &args.signatures,
            &args.reports,
            &args.output,
        ),
        safety: Safety {
            read_only_scanner: true,
            uses_live_malware: false,
            executes_scanned_files: false,
            mutates_scanned_files: false,
            network_actions: false,
            fixture_note: "Current Rust demo uses the official EICAR safe anti-malware test file generated by the Rust prepare-eicar-demo command; no live malware is used.".to_string(),
        },
    };

    if let Some(parent) = args.output.parent() {
        fs::create_dir_all(parent).map_err(|err| {
            format!(
                "could not create evidence directory {}: {err}",
                parent.display()
            )
        })?;
    }
    let text = serde_json::to_string_pretty(&manifest)
        .map_err(|err| format!("could not serialize evidence manifest: {err}"))?;
    fs::write(&args.output, format!("{text}\n")).map_err(|err| {
        format!(
            "could not write evidence manifest {}: {err}",
            args.output.display()
        )
    })
}

fn demo_tree_evidence(target: &Path) -> Result<Vec<FileEvidence>, String> {
    let mut files = Vec::new();
    if target.is_file() {
        files.push(file_evidence(target, target.parent().unwrap_or(target))?);
    } else {
        for path in collect_regular_files(target)? {
            files.push(file_evidence(&path, target)?);
        }
    }
    files.sort_by(|left, right| left.path.cmp(&right.path));
    Ok(files)
}

fn report_evidence(path: &Path) -> Result<ReportEvidence, String> {
    let base = file_evidence(path, &project_root())?;
    let parsed = if path.extension().and_then(|value| value.to_str()) == Some("json") {
        let text = fs::read_to_string(path)
            .map_err(|err| format!("could not read JSON report {}: {err}", path.display()))?;
        serde_json::from_str::<Value>(&text).ok()
    } else {
        None
    };

    Ok(ReportEvidence {
        path: base.path,
        sha256: base.sha256,
        size_bytes: base.size_bytes,
        tool: parsed.as_ref().and_then(|value| value.get("tool").cloned()),
        target: parsed
            .as_ref()
            .and_then(|value| value.get("target").cloned()),
        summary: parsed
            .as_ref()
            .and_then(|value| value.get("summary").cloned()),
        scan_metadata: parsed
            .as_ref()
            .and_then(|value| value.get("scan_metadata").cloned()),
    })
}

fn collect_regular_files(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();
    collect_regular_files_inner(root, &mut files)?;
    files.sort();
    Ok(files)
}

fn collect_regular_files_inner(root: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(root)
        .map_err(|err| format!("could not read directory {}: {err}", root.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| {
            format!(
                "could not read directory entry under {}: {err}",
                root.display()
            )
        })?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let metadata = fs::symlink_metadata(&path)
            .map_err(|err| format!("could not read metadata for {}: {err}", path.display()))?;
        if metadata.file_type().is_symlink() {
            continue;
        }
        if metadata.is_file() {
            files.push(path);
        } else if metadata.is_dir() {
            collect_regular_files_inner(&path, files)?;
        }
    }
    Ok(())
}

fn file_evidence(path: &Path, base: &Path) -> Result<FileEvidence, String> {
    let metadata = fs::metadata(path)
        .map_err(|err| format!("could not read metadata for {}: {err}", path.display()))?;
    Ok(FileEvidence {
        path: display_relative_path(path, base),
        sha256: sha256_file(path)?,
        size_bytes: metadata.len(),
    })
}

fn sha256_file(path: &Path) -> Result<String, String> {
    let bytes =
        fs::read(path).map_err(|err| format!("could not read {}: {err}", path.display()))?;
    let digest = Sha256::digest(&bytes);
    Ok(format!("{digest:x}"))
}

fn reproducibility(
    target: &Path,
    signatures: &Path,
    reports: &[PathBuf],
    output: &Path,
) -> Reproducibility {
    let json_report = reports
        .iter()
        .find(|path| path.extension().and_then(|value| value.to_str()) == Some("json"))
        .cloned()
        .unwrap_or_else(|| PathBuf::from("../reports/demo-report.json"));
    let markdown_report = reports
        .iter()
        .find(|path| path.extension().and_then(|value| value.to_str()) == Some("md"))
        .cloned()
        .unwrap_or_else(|| PathBuf::from("../reports/demo-report.md"));

    Reproducibility {
        format_command: "cargo fmt --check".to_string(),
        test_command: "cargo test".to_string(),
        lint_command: "cargo clippy --all-targets -- -D warnings".to_string(),
        signature_validation_command: format!(
            "cargo run -- validate-signatures --signatures {}",
            target_arg(signatures)
        ),
        eicar_preparation_command: format!("cargo run -- prepare-eicar-demo --target {}", target_arg(target)),
        demo_verification_command: format!(
            "cargo run -- verify-demo --target {} --signatures {}",
            target_arg(target),
            target_arg(signatures)
        ),
        scan_command: format!(
            "cargo run -- scan --target {} --signatures {} --json {} --markdown {}",
            target_arg(target),
            target_arg(signatures),
            target_arg(&json_report),
            target_arg(&markdown_report)
        ),
        evidence_manifest_command: format!(
            "cargo run -- write-evidence --target {} --signatures {} --report {} --report {} --output {}",
            target_arg(target),
            target_arg(signatures),
            target_arg(&json_report),
            target_arg(&markdown_report),
            target_arg(output)
        ),
    }
}

fn target_kind(path: &Path) -> String {
    if path.is_dir() {
        "directory".to_string()
    } else {
        "file".to_string()
    }
}

fn existing_path(path: &Path) -> Result<PathBuf, String> {
    let absolute = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .map_err(|err| format!("could not read current directory: {err}"))?
            .join(path)
    };
    absolute.canonicalize().map_err(|err| {
        format!(
            "path does not exist or cannot be resolved {}: {err}",
            path.display()
        )
    })
}

fn display_project_path(path: &Path) -> String {
    display_relative_path(path, &project_root())
}

fn display_relative_path(path: &Path, base: &Path) -> String {
    path.strip_prefix(base)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

fn target_arg(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("rust folder should have a project parent")
        .to_path_buf()
}
